apiVersion: v2
name: first-child
description: Helm chart for child chart.

version: 0.0.55
type: application

dependencies:
  - name: todolist
    version: "0.2.0"
    repository: file://../../../helm/todolist
